### ISSUE TITLE
python3 shim

### ISSUE THREAD

**Issue by lainisourgod** [kkysen/pyenv-python#2]
Hi!

Thanks for great project! It improved my developer experience a lot!

However I had a problem that `poetry` uses shebang `#!/usr/bin/env python3`, which evaluates to my system python version and not to `python` shim from `~/.cargo/bin` because there is no shim `python3` there.

I fixed this by doing `ln -s ~/.cargo/bin/python ~/.cargo/bin/python3`.

Is it problem with my configuration or this code?

**Comment by kkysen** [comment]
Hi!  Sorry I didn't see this earlier.  I'm glad people are using it and it's been useful!

You're right, you need to make symlinks from `$CARGO_HOME/bin/python` to any other executables you want to run using it.  That includes binaries like `python3` and scripts like `youtube-dl`, anything not named `python`.  The actual executables will need to be siblings to the main `python` executable, which is how things are installed by default.  And then your symlinks can go anywhere in `$PATH`, like `$CARGO_HOME/bin` if you want.

I tried to make this clearer in the updated README.md.  I also released a new version that has better internal APIs and fixes a couple of bugs.

Let me know if you still have any trouble getting things to work.
